import { BASE_URL, BASE_WITH_JOURNEY_TYPE_AND_IDS_URL, GENERAL_PARTNER_WITH_ID_URL, LIMITED_PARTNER_WITH_ID_URL, POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL, POST_TRANSITION_WITH_IDS_URL, TRANSACTION_SUBMISSION_URL } from "../../../config/constants";
import GlobalPageType from "./PageType";
import { SIGN_OUT_TEMPLATE } from "./template";

export const HEALTHCHECK_URL = `${BASE_URL}/healthcheck`;
export const SIGN_OUT_URL = `${BASE_URL}/${SIGN_OUT_TEMPLATE}`;
export const PAYMENT_RESPONSE_URL = `${BASE_WITH_JOURNEY_TYPE_AND_IDS_URL}/${GlobalPageType.paymentResponse}`;
export const PAYMENT_FAILED_URL = `${BASE_WITH_JOURNEY_TYPE_AND_IDS_URL}/${GlobalPageType.paymentFailed}`;
export const CONFIRMATION_URL = `${BASE_WITH_JOURNEY_TYPE_AND_IDS_URL}/${GlobalPageType.confirmation}`;
export const CONFIRMATION_POST_TRANSITION_URL = `${POST_TRANSITION_WITH_IDS_URL}/${GlobalPageType.confirmation}`;
export const RESUME = "/resume";
export const RESUME_JOURNEY_REGISTRATION_OR_TRANSITION_URL = `${BASE_URL}${TRANSACTION_SUBMISSION_URL}${RESUME}`;
export const RESUME_JOURNEY_POST_TRANSITION_GENERAL_PARTNER_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}${RESUME}`;
export const RESUME_JOURNEY_POST_TRANSITION_LIMITED_PARTNER_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}${RESUME}`;
export const RESUME_JOURNEY_POST_TRANSITION_PARTNERSHIP_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}${RESUME}`;
