import * as template from "./template";

import {
  REGISTRATION_BASE_URL,
  REGISTRATION_WITH_IDS_URL,
  GENERAL_PARTNER_WITH_ID_URL,
  LIMITED_PARTNER_WITH_ID_URL
} from "../../../config/constants";

export const WHICH_TYPE_URL = `${REGISTRATION_BASE_URL}/${template.WHICH_TYPE_TEMPLATE}`;
export const WHICH_TYPE_WITH_IDS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.WHICH_TYPE_TEMPLATE}`;
export const NAME_URL = `${REGISTRATION_BASE_URL}/${template.NAME_TEMPLATE}`;
export const NAME_WITH_IDS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.NAME_TEMPLATE}`;
export const EMAIL_URL = `${REGISTRATION_WITH_IDS_URL}/${template.EMAIL_TEMPLATE}`;
export const WHERE_IS_THE_JURISDICTION_URL = `${REGISTRATION_WITH_IDS_URL}/${template.WHERE_IS_THE_JURISDICTION_TEMPLATE}`;
export const TERM_URL = `${REGISTRATION_WITH_IDS_URL}/${template.TERM_TEMPLATE}`;
export const SIC_URL = `${REGISTRATION_WITH_IDS_URL}/${template.SIC_TEMPLATE}`;

// general partner
export const GENERAL_PARTNERS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.GENERAL_PARTNERS_TEMPLATE}`;
export const GENERAL_PARTNER_CHOICE_URL = `${REGISTRATION_WITH_IDS_URL}/${template.GENERAL_PARTNER_CHOICE_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_PERSON_URL = `${REGISTRATION_WITH_IDS_URL}/${template.ADD_GENERAL_PARTNER_PERSON_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_PERSON_WITH_ID_URL = `${REGISTRATION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ADD_GENERAL_PARTNER_PERSON_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_URL = `${REGISTRATION_WITH_IDS_URL}/${template.ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_WITH_ID_URL = `${REGISTRATION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const REVIEW_GENERAL_PARTNERS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.REVIEW_GENERAL_PARTNERS_TEMPLATE}`;
export const REMOVE_GENERAL_PARTNER_URL = `${REGISTRATION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.REMOVE_GENERAL_PARTNER_TEMPLATE}`;

// limited partner
export const LIMITED_PARTNERS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.LIMITED_PARTNERS_TEMPLATE}`;
export const LIMITED_PARTNER_CHOICE_URL = `${REGISTRATION_WITH_IDS_URL}/${template.LIMITED_PARTNER_CHOICE_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_PERSON_URL = `${REGISTRATION_WITH_IDS_URL}/${template.ADD_LIMITED_PARTNER_PERSON_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_PERSON_WITH_ID_URL = `${REGISTRATION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.ADD_LIMITED_PARTNER_PERSON_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_LEGAL_ENTITY_URL = `${REGISTRATION_WITH_IDS_URL}/${template.ADD_LIMITED_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_LEGAL_ENTITY_WITH_ID_URL = `${REGISTRATION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.ADD_LIMITED_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const REVIEW_LIMITED_PARTNERS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.REVIEW_LIMITED_PARTNERS_TEMPLATE}`;
export const REMOVE_LIMITED_PARTNER_URL = `${REGISTRATION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.REMOVE_LIMITED_PARTNER_TEMPLATE}`;

export const CHECK_YOUR_ANSWERS_URL = `${REGISTRATION_WITH_IDS_URL}/${template.CHECK_YOUR_ANSWERS_TEMPLATE}`;
export const NEXT_URL = `${REGISTRATION_WITH_IDS_URL}/${template.NEXT_TEMPLATE}`;
