import PostTransitionPageType from "./pageType";

export const COMPANY_NUMBER_TEMPLATE = PostTransitionPageType.companyNumber;
export const CONFIRM_LIMITED_PARTNERSHIP_TEMPLATE = PostTransitionPageType.confirmLimitedPartnership;
export const LANDING_PAGE_TEMPLATE = PostTransitionPageType.landingPage;

// general partner
export const GENERAL_PARTNER_CHOICE_TEMPLATE = PostTransitionPageType.generalPartnerType;
export const ADD_GENERAL_PARTNER_PERSON_TEMPLATE = PostTransitionPageType.addGeneralPartnerPerson;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE = PostTransitionPageType.addGeneralPartnerLegalEntity;
export const GENERAL_PARTNER_CHECK_YOUR_ANSWERS_TEMPLATE = PostTransitionPageType.generalPartnerCheckYourAnswers;

// limited partner
export const LIMITED_PARTNER_CHOICE_TEMPLATE = PostTransitionPageType.limitedPartnerType;
export const ADD_LIMITED_PARTNER_PERSON_TEMPLATE = PostTransitionPageType.addLimitedPartnerPerson;
export const ADD_LIMITED_PARTNER_LEGAL_ENTITY_TEMPLATE = PostTransitionPageType.addLimitedPartnerLegalEntity;
export const LIMITED_PARTNER_CHECK_YOUR_ANSWERS_TEMPLATE = PostTransitionPageType.limitedPartnerCheckYourAnswers;

// limited partnership
export const ENTER_REGISTERED_OFFICE_ADDRESSS_TEMPLATE = PostTransitionPageType.enterRegisteredOfficeAddress;
export const WHEN_DID_THE_REGISTERED_OFFICE_ADDRESS_CHANGE_TEMPLATE =
  PostTransitionPageType.whenDidTheRegisteredOfficeAddressChange;
export const REGISTERED_OFFICE_ADDRESS_CHANGE_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.registeredOfficeAddressChangeCheckYourAnswers;

export const PARTNERSHIP_NAME_TEMPLATE = PostTransitionPageType.partnershipName;
export const WHEN_DID_THE_PARTNERSHIP_NAME_CHANGE_TEMPLATE = PostTransitionPageType.whenDidThePartnershipNameChange;
export const PARTNERSHIP_NAME_CHANGE_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.partnershipNameChangeCheckYourAnswers;

export const TERM_TEMPLATE = PostTransitionPageType.term;
export const WHEN_DID_TERM_CHANGE_TEMPLATE = PostTransitionPageType.whenDidTheTermChange;
export const TERM_CHANGE_CHECK_YOUR_ANSWERS_TEMPLATE = PostTransitionPageType.termChangeCheckYourAnswers;

export const ENTER_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE =
  PostTransitionPageType.enterPrincipalPlaceOfBusinessAddress;
export const WHEN_DID_THE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_CHANGE_TEMPLATE =
  PostTransitionPageType.whenDidThePrincipalPlaceOfBusinessAddressChange;
export const PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_CHANGE_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.principalPlaceOfBusinessAddressChangeCheckYourAnswers;

export const WHEN_DID_THE_GENERAL_PARTNER_PERSON_CEASE_TEMPLATE =
  PostTransitionPageType.whenDidTheGeneralPartnerPersonCease;
export const REMOVE_GENERAL_PARTNER_PERSON_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.removeGeneralPartnerPersonCheckYourAnswers;

export const WHEN_DID_THE_GENERAL_PARTNER_LEGAL_ENTITY_CEASE_TEMPLATE =
  PostTransitionPageType.whenDidTheGeneralPartnerLegalEntityCease;
export const REMOVE_GENERAL_PARTNER_LEGAL_ENTITY_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.removeGeneralPartnerLegalEntityCheckYourAnswers;

export const WHEN_DID_THE_LIMITED_PARTNER_PERSON_CEASE_TEMPLATE =
  PostTransitionPageType.whenDidTheLimitedPartnerPersonCease;
export const REMOVE_LIMITED_PARTNER_PERSON_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.removeLimitedPartnerPersonCheckYourAnswers;
export const WHEN_DID_THE_LIMITED_PARTNER_LEGAL_ENTITY_CEASE_TEMPLATE =
  PostTransitionPageType.whenDidTheLimitedPartnerLegalEntityCease;
export const REMOVE_LIMITED_PARTNER_LEGAL_ENTITY_CHECK_YOUR_ANSWERS_TEMPLATE =
  PostTransitionPageType.removeLimitedPartnerLegalEntityCheckYourAnswers;
export const REDESIGNATE_TO_PFLP_TEMPLATE = PostTransitionPageType.redesignateToPflp;

export const UPDATE_GENERAL_PARTNER_PERSON_TEMPLATE = PostTransitionPageType.updateGeneralPartnerPerson;
