import PostTransitionPageType from "./pageType";

export const COMPANY_NUMBER_TEMPLATE = PostTransitionPageType.companyNumber;
export const CONFIRM_LIMITED_PARTNERSHIP_TEMPLATE = PostTransitionPageType.confirmLimitedPartnership;
export const LANDING_PAGE_TEMPLATE = PostTransitionPageType.landingPage;

// general partner
export const GENERAL_PARTNER_CHOICE_TEMPLATE = PostTransitionPageType.generalPartnerChoice;
export const ADD_GENERAL_PARTNER_PERSON_TEMPLATE = PostTransitionPageType.addGeneralPartnerPerson;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE = PostTransitionPageType.addGeneralPartnerLegalEntity;
export const GENERAL_PARTNER_CHECK_YOUR_ANSWERS_TEMPLATE = PostTransitionPageType.generalPartnerCheckYourAnswers;

// general partner
export const LIMITED_PARTNER_CHOICE_TEMPLATE = PostTransitionPageType.limitedPartnerChoice;
export const ADD_LIMITED_PARTNER_PERSON_TEMPLATE = PostTransitionPageType.addLimitedPartnerPerson;
export const ADD_LIMITED_PARTNER_LEGAL_ENTITY_TEMPLATE = PostTransitionPageType.addLimitedPartnerLegalEntity;
export const LIMITED_PARTNER_CHECK_YOUR_ANSWERS_TEMPLATE = PostTransitionPageType.limitedPartnerCheckYourAnswers;
