import PostTransitionPageType from "./pageType";

export const COMPANY_NUMBER_TEMPLATE = PostTransitionPageType.companyNumber;
export const CONFIRM_LIMITED_PARTNERSHIP_TEMPLATE = PostTransitionPageType.confirmLimitedPartnership;

export const GENERAL_PARTNER_CHOICE_TEMPLATE = PostTransitionPageType.generalPartnerChoice;
export const ADD_GENERAL_PARTNER_PERSON_TEMPLATE = PostTransitionPageType.addGeneralPartnerPerson;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE = PostTransitionPageType.addGeneralPartnerLegalEntity;

