import {
  GENERAL_PARTNER_WITH_ID_URL,
  LIMITED_PARTNER_WITH_ID_URL,
  POST_TRANSITION_BASE_URL,
  POST_TRANSITION_WITH_ID_URL,
  POST_TRANSITION_WITH_IDS_URL,
  POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL
} from "../../../config/constants";
import * as template from "./template";

export const COMPANY_NUMBER_URL = `${POST_TRANSITION_BASE_URL}/${template.COMPANY_NUMBER_TEMPLATE}`;
export const CONFIRM_LIMITED_PARTNERSHIP_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.CONFIRM_LIMITED_PARTNERSHIP_TEMPLATE}`;
export const LANDING_PAGE_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.LANDING_PAGE_TEMPLATE}`;

// general partner
export const GENERAL_PARTNER_CHOICE_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.GENERAL_PARTNER_CHOICE_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_PERSON_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.ADD_GENERAL_PARTNER_PERSON_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_PERSON_WITH_IDS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ADD_GENERAL_PARTNER_PERSON_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const ADD_GENERAL_PARTNER_LEGAL_ENTITY_WITH_IDS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ADD_GENERAL_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const GENERAL_PARTNER_CHECK_YOUR_ANSWERS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.GENERAL_PARTNER_CHECK_YOUR_ANSWERS_TEMPLATE}`;

// limited partner
export const LIMITED_PARTNER_CHOICE_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.LIMITED_PARTNER_CHOICE_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_PERSON_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.ADD_LIMITED_PARTNER_PERSON_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_PERSON_WITH_IDS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.ADD_LIMITED_PARTNER_PERSON_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_LEGAL_ENTITY_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.ADD_LIMITED_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const ADD_LIMITED_PARTNER_LEGAL_ENTITY_WITH_IDS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.ADD_LIMITED_PARTNER_LEGAL_ENTITY_TEMPLATE}`;
export const LIMITED_PARTNER_CHECK_YOUR_ANSWERS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.LIMITED_PARTNER_CHECK_YOUR_ANSWERS_TEMPLATE}`;

// limited partnership
export const ENTER_REGISTERED_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_ID_URL}/${template.ENTER_REGISTERED_OFFICE_ADDRESSS_TEMPLATE}`;
export const ENTER_REGISTERED_OFFICE_ADDRESS_WITH_IDS_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}/${template.ENTER_REGISTERED_OFFICE_ADDRESSS_TEMPLATE}`;
export const WHEN_DID_THE_REGISTERED_OFFICE_ADDRESS_CHANGE_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}/${template.WHEN_DID_THE_REGISTERED_OFFICE_ADDRESS_CHANGE_TEMPLATE}`;
export const REGISTERED_OFFICE_ADDRESS_CHANGE_CHECK_YOUR_ANSWERS_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}/${template.REGISTERED_OFFICE_ADDRESS_CHANGE_CHECK_YOUR_ANSWERS_TEMPLATE}`;

export const PARTNERSHIP_NAME_WITH_IDS_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}/${template.PARTNERSHIP_NAME_TEMPLATE}`;
export const WHEN_DID_THE_PARTNERSHIP_NAME_CHANGE_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}/${template.WHEN_DID_THE_PARTNERSHIP_NAME_CHANGE_TEMPLATE}`;
export const PARTNERSHIP_NAME_CHANGE_CHECK_YOUR_ANSWERS_URL = `${POST_TRANSITION_WITH_IDS_AND_SUBMISSION_URL}/${template.PARTNERSHIP_NAME_CHANGE_CHECK_YOUR_ANSWERS_TEMPLATE}`;
