import { POST_TRANSITION_BASE_URL } from "../../../config/constants";
import * as template from "./template";

export const COMPANY_NUMBER_URL = `${POST_TRANSITION_BASE_URL}/${template.COMPANY_NUMBER_TEMPLATE}`;
export const CONFIRM_LIMITED_PARTNERSHIP_URL = `${POST_TRANSITION_BASE_URL}/${template.CONFIRM_LIMITED_PARTNERSHIP_TEMPLATE}`;
export const LANDING_PAGE_URL = `${POST_TRANSITION_BASE_URL}/${template.LANDING_PAGE_TEMPLATE}`;

// general partner
export const GENERAL_PARTNER_CHOICE_URL = `${POST_TRANSITION_BASE_URL}/${template.GENERAL_PARTNER_CHOICE_TEMPLATE}`;
