import * as template from "../template";

import {
  POST_TRANSITION_WITH_IDS_URL,
  GENERAL_PARTNER_WITH_ID_URL,
  LIMITED_PARTNER_WITH_ID_URL
} from "../../../../config/constants";

// GENERAL PARTNER

// usual residential address - Person
export const UPDATE_USUAL_RESIDENTIAL_ADDRESS_YES_NO_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.UPDATE_USUAL_RESIDENTIAL_ADDRESS_YES_NO_TEMPLATE}`;
export const TERRITORY_CHOICE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.TERRITORY_CHOICE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const POSTCODE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.POSTCODE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const ENTER_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ENTER_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const CHOOSE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CHOOSE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const CONFIRM_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CONFIRM_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;

// correspondence address - Person
export const TERRITORY_CHOICE_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.TERRITORY_CHOICE_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_TEMPLATE}`;
export const POSTCODE_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.POSTCODE_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_TEMPLATE}`;
export const CHOOSE_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CHOOSE_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_TEMPLATE}`;
export const ENTER_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ENTER_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_TEMPLATE}`;
export const CONFIRM_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CONFIRM_GENERAL_PARTNER_CORRESPONDENCE_ADDRESS_TEMPLATE}`;

// principal office address - Legal Entity

export const TERRITORY_CHOICE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.TERRITORY_CHOICE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const POSTCODE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.POSTCODE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const CHOOSE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CHOOSE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const ENTER_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ENTER_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const CONFIRM_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CONFIRM_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;

// LIMITED PARTNER

// usual residential address - Person
export const TERRITORY_CHOICE_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.TERRITORY_CHOICE_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const POSTCODE_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.POSTCODE_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const ENTER_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.ENTER_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const CHOOSE_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.CHOOSE_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
export const CONFIRM_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.CONFIRM_LIMITED_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;

// principal office address - Legal Entity
export const TERRITORY_CHOICE_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.TERRITORY_CHOICE_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const POSTCODE_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.POSTCODE_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const CHOOSE_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.CHOOSE_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const ENTER_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.ENTER_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const CONFIRM_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${LIMITED_PARTNER_WITH_ID_URL}/${template.CONFIRM_LIMITED_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
