import * as template from "../template";

import { POST_TRANSITION_WITH_IDS_URL, GENERAL_PARTNER_WITH_ID_URL } from "../../../../config/constants";

// principal office address - Legal Entity

export const TERRITORY_CHOICE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.TERRITORY_CHOICE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const POSTCODE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.POSTCODE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const CHOOSE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CHOOSE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const ENTER_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.ENTER_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
export const CONFIRM_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_URL = `${POST_TRANSITION_WITH_IDS_URL}${GENERAL_PARTNER_WITH_ID_URL}/${template.CONFIRM_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRESS_TEMPLATE}`;
