import AddressPageType from "./PageType";

// LIMITED PARTNERSHIP

// Registered Office Address
export const POSTCODE_REGISTERED_OFFICE_ADDRESS_TEMPLATE =
  AddressPageType.postcodeRegisteredOfficeAddress;
export const CHOOSE_REGISTERED_OFFICE_ADDRESS_TEMPLATE =
  AddressPageType.chooseRegisteredOfficeAddress;
export const ENTER_REGISTERED_OFFICE_ADDRESS_TEMPLATE =
  AddressPageType.enterRegisteredOfficeAddress;
export const CONFIRM_REGISTERED_OFFICE_ADDRESS_TEMPLATE =
  AddressPageType.confirmRegisteredOfficeAddress;

// principal place of business
export const POSTCODE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE =
  AddressPageType.postcodePrincipalPlaceOfBusinessAddress;
export const CHOOSE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE =
  AddressPageType.choosePrincipalPlaceOfBusinessAddress;
export const ENTER_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE =
  AddressPageType.enterPrincipalPlaceOfBusinessAddress;
export const CONFIRM_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE =
  AddressPageType.confirmPrincipalPlaceOfBusinessAddress;

// GENERAL PARTNER

// usual residential address
export const TERRITORY_CHOICE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE =
  AddressPageType.territoryChoiceGeneralPartnerUsualResidentialAddress;
export const POSTCODE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE =
  AddressPageType.postcodeGeneralPartnerUsualResidentialAddress;
export const CHOOSE_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE =
  AddressPageType.chooseGeneralPartnerUsualResidentialAddress;
export const ENTER_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE =
  AddressPageType.enterGeneralPartnerUsualResidentialAddress;
export const CONFIRM_GENERAL_PARTNER_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE =
  AddressPageType.confirmGeneralPartnerUsualResidentialAddress;
export const POSTCODE_GENERAL_PARTNER_PRINCIPAL_OFFICE_ADDRES_TEMPLATE = 
  AddressPageType.postcodeGeneralPartnerPrincipalOfficeAddress;