import * as template from "./template";

import { BASE_WITH_IDS_URL } from "../../../config/constants";

// LIMITED PARTNERSHIP

// registered office address
export const POSTCODE_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.POSTCODE_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const CHOOSE_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.CHOOSE_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const ENTER_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.ENTER_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const CONFIRM_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.CONFIRM_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;

// principal place of business
export const POSTCODE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.POSTCODE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE}`;
export const CHOOSE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.CHOOSE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE}`;
export const ENTER_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.ENTER_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE}`;
export const CONFIRM_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.CONFIRM_RINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE}`;

// GENERAL PARTNER

// usual residential address
export const POSTCODE_USUAL_RESIDENTIAL_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.POSTCODE_USUAL_RESIDENTIAL_ADDRESS_TEMPLATE}`;
