import * as template from "./template";

import { BASE_WITH_IDS_URL } from "../../../config/constants";

export const POSTCODE_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.POSTCODE_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const CHOOSE_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.CHOOSE_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const ENTER_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.ENTER_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const CONFIRM_REGISTERED_OFFICE_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.CONFIRM_REGISTERED_OFFICE_ADDRESS_TEMPLATE}`;
export const CHOOSE_PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_URL = `${BASE_WITH_IDS_URL}/${template.PRINCIPAL_PLACE_OF_BUSINESS_ADDRESS_TEMPLATE}`;
